spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  http:
     encoding:
       charset: UTF-8
       force: true
       enabled: true
  activiti:
    check-process-definitions: false

server:
  port: 80

mybatis:
  type-aliases-package: com.dream.dflow.entity
  mapper-locations: classpath:mapper/*.xml

d-Address:
  processLocation: processes

